// Display translations only; native identities and save fields stay unchanged.
// Terminology and retained English: LOCALIZATION.md.
var cnItems = {
    "RANDOM": "随机",
    "fight": "战斗",
    "back_down": "退让",
    "discrete": "离散",
    "continuous": "连续",
    "particle": "粒子",
    "wave": "波",
    "go": "前进",
    "stay": "停留",
    "search": "搜索",
    "evaluate": "评估",
    "attack": "攻击",
    "decay": "衰减",
    "raise_price": "提价",
    "lower_price": "降价",
    "swerve": "转向",
    "straight": "直行",
    "macro": "宏观",
    "micro": "微观",
    "cooperate": "合作",
    "defect": "背叛",
    "football": "足球",
    "opera": "歌剧",
    "accept": "接受",
    "reject": "拒绝",
    "lead": "领导",
    "follow": "跟随",
    "fold": "弃牌",
    "bet": "下注",
    "tails": "反面",
    "heads": "正面",
    "deny": "否认",
    "A100": "A100",
    "B100": "B100",
    "GREEDY": "贪婪",
    "GENEROUS": "慷慨",
    "BEAT LAST": "击败上轮",
    "TIT FOR TAT": "针锋相对",
    "MINIMAX": "最小最大",
    "peace": "和平",
    "war": "战争",
    "Aboukir": "阿布基尔",
    "Abensberg": "阿本斯贝格",
    "Acre": "阿克",
    "Alba de Tormes": "托尔梅斯河畔阿尔瓦",
    "la Albuera": "阿尔武埃拉",
    "Algeciras Bay": "阿尔赫西拉斯湾",
    "Amstetten": "阿姆施泰滕",
    "Arcis-sur-Aube": "奥布河畔阿尔西",
    "Aspern-Essling": "阿斯佩恩—埃斯灵",
    "Jena-Auerstedt": "耶拿—奥尔施泰特",
    "Arcole": "阿尔科莱",
    "Austerlitz": "奥斯特利茨",
    "Badajoz": "巴达霍斯",
    "Bailen": "拜伦",
    "la Barrosa": "巴罗萨",
    "Bassano": "巴萨诺",
    "Bautzen": "包岑",
    "Berezina": "别列津纳河",
    "Bergisel": "贝尔吉瑟尔",
    "Borodino": "博罗金诺",
    "Burgos": "布尔戈斯",
    "Bucaco": "布萨科",
    "Cadiz": "加的斯",
    "Caldiero": "卡尔迪耶罗",
    "Castiglione": "卡斯蒂廖内",
    "Castlebar": "卡斯尔巴",
    "Champaubert": "尚波贝尔",
    "Chateau-Thierry": "蒂埃里堡",
    "Copenhagen": "哥本哈根",
    "Corunna": "拉科鲁尼亚",
    "Craonne": "克拉奥讷",
    "Dego": "代戈",
    "Dennewitz": "登讷维茨",
    "Dresden": "德累斯顿",
    "Durenstein": "迪恩施泰因",
    "Eckmuhl": "埃克米尔",
    "Elchingen": "埃尔兴根",
    "Espinosa de los Monteros": "埃斯皮诺萨德洛斯蒙特罗斯",
    "Eylau": "埃劳",
    "Cape Finisterre": "菲尼斯特雷角",
    "Friedland": "弗里德兰",
    "Fuentes de Onoro": "丰特斯德奥尼奥罗",
    "Gevora River": "赫沃拉河",
    "Gerona": "赫罗纳",
    "Wagram": "瓦格拉姆",
    "Waterloo": "滑铁卢",
    "Wavre": "瓦夫尔",
    "Wertingen": "韦尔廷根",
    "Zaragoza": "萨拉戈萨",
    "Hamburg": "汉堡",
    "Heilsberg": "海尔斯贝格",
    "Hohenlinden": "霍恩林登",
    "Landshut": "兰茨胡特",
    "Leipzig": "莱比锡",
    "Ligny": "利尼",
    "Lodi": "洛迪",
    "Lubeck": "吕贝克",
    "Lutzen": "吕岑",
    "Marengo": "马伦戈",
    "Medellin": "麦德林",
    "Mincio River": "明乔河",
    "Mondovi": "蒙多维",
    "Montebello": "蒙特贝洛",
    "Montenotte": "蒙特诺特",
    "Montmirail": "蒙米拉伊",
    "Mount Tabor": "塔博尔山",
    "The Nile": "尼罗河",
    "Ocana": "奥卡尼亚",
    "Cape Ortegal": "奥特加尔角",
    "Orthez": "奥尔泰兹",
    "Pancorbo": "潘科尔博",
    "Piave River": "皮亚韦河",
    "The Pyramids": "金字塔",
    "Quatre Bras": "四臂村",
    "Raab": "拉布",
    "Rivoli": "里沃利",
    "Rovereto": "罗韦雷托",
    "Saalfeld": "萨尔费尔德",
    "Salamanca": "萨拉曼卡",
    "Smolensk": "斯摩棱斯克",
    "Somosierra": "索莫谢拉",
    "Talavera": "塔拉韦拉",
    "Trafalgar": "特拉法加",
    "Trebbia": "特雷比亚河",
    "Tudela": "图德拉",
    "Ulm": "乌尔姆",
    "Valls": "瓦尔斯",
    "Vimeiro": "维梅罗",
    "Vitoria": "维多利亚"
};

function cnItem(text) {
    return Object.prototype.hasOwnProperty.call(cnItems, text) ? cnItems[text] : text;
}

// Render historic labels in Chinese without changing their raw save values.
function localizeBattleName(text) {
    var translated = String(text).replace(/\bDrifter Attack(?=\s+\d+\b)/g, '漂流者袭击');
    for (var name in cnItems) {
        var escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        translated = translated.replace(new RegExp('(^|\\s)(' + escaped + ')(\\s+\\d+)(?=$|\\s)', 'g'),
            function (match, prefix, key, number) { return prefix + cnItem(key) + number; });
    }
    return translated;
}

function cntitle(text) { return text; }
